  bugfix/fix-local-urls[m
  correction[m
  cursor-pointer[m
* [32mdevelop[m
  feat/ay11[m
  feat/button-interactions[m
  feat/dev-3[m
  feat/dialog[m
  feat/dialog-implementation[m
  feat/linter[m
  feat/pop-in[m
  feat/proto/swiper[m
  fix/assets[m
  fix/responsiveness[m
  gh-pages[m
  links-to-outside[m
  main[m
  merge/slidermap[m
  pop-in-contact[m
  proto/desktop/1[m
  proto/swiper[m
  responsive[m
  seine-zoom-map[m
  slider/map[m
